// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NGenericDimensions.CodeGenerator
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class T4DimensionUnitOfMeasure : T4DimensionUnitOfMeasureBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 6 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
  if (dimensionUnitOfMeasureBase.Is2DInterface || dimensionUnitOfMeasureBase.Is3DInterface) { 
            
            #line default
            #line hidden
            this.Write("using NGenericDimensions.");
            
            #line 7 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dimensionUnitOfMeasureBase.Dimension.BaseDimensionsThisDerivedFrom[0].BaseDimension.NamePluralUppercase));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n");
            
            #line 9 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
  } 
            
            #line default
            #line hidden
            
            #line 10 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
  if (dimensionUnitOfMeasureBase.SubFolder == null) { 
            
            #line default
            #line hidden
            this.Write("namespace NGenericDimensions.");
            
            #line 11 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dimensionUnitOfMeasureBase.Dimension.NamePluralUppercase));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 12 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write("namespace NGenericDimensions.");
            
            #line 13 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dimensionUnitOfMeasureBase.Dimension.NamePluralUppercase));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 13 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dimensionUnitOfMeasureBase.SubFolder));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 14 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
  } 
            
            #line default
            #line hidden
            this.Write("{\r\n");
            
            #line 16 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
  if (dimensionUnitOfMeasureBase.UnitGroupName != null) { 
            
            #line default
            #line hidden
            this.Write("    public abstract class ");
            
            #line 17 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dimensionUnitOfMeasureBase.InterfaceName));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 17 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dimensionUnitOfMeasureBase.BaseInterface.InterfaceName));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 18 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
  } else if (dimensionUnitOfMeasureBase.Is1DInterface) { 
            
            #line default
            #line hidden
            this.Write("    public abstract class ");
            
            #line 19 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dimensionUnitOfMeasureBase.InterfaceName));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 19 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dimensionUnitOfMeasureBase.Dimension.NameUppercase));
            
            #line default
            #line hidden
            this.Write("UnitOfMeasure, IExponent1Or2, IExponent1Or3\r\n");
            
            #line 20 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
  } else if (dimensionUnitOfMeasureBase.Is2DInterface) { 
            
            #line default
            #line hidden
            this.Write("    public abstract class ");
            
            #line 21 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dimensionUnitOfMeasureBase.InterfaceName));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 21 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dimensionUnitOfMeasureBase.Dimension.BaseDimensionsThisDerivedFrom[0].BaseDimension.NameUppercase));
            
            #line default
            #line hidden
            this.Write("UnitOfMeasure, IExponent1Or2\r\n");
            
            #line 22 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
  } else if (dimensionUnitOfMeasureBase.Is3DInterface) { 
            
            #line default
            #line hidden
            this.Write("    public abstract class ");
            
            #line 23 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dimensionUnitOfMeasureBase.InterfaceName));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 23 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dimensionUnitOfMeasureBase.Dimension.BaseDimensionsThisDerivedFrom[0].BaseDimension.NameUppercase));
            
            #line default
            #line hidden
            this.Write("UnitOfMeasure, IExponent1Or3\r\n");
            
            #line 24 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write("    public abstract class ");
            
            #line 25 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dimensionUnitOfMeasureBase.InterfaceName));
            
            #line default
            #line hidden
            this.Write(" : UnitOfMeasure\r\n");
            
            #line 26 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
  } 
            
            #line default
            #line hidden
            this.Write("    {\r\n");
            
            #line 28 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
  if (dimensionUnitOfMeasureBase.NonFamilyMultiplier != null && dimensionUnitOfMeasureBase.NonFamilyMultiplier != "1") { 
            
            #line default
            #line hidden
            this.Write("        protected override double GetMultiplier(bool stayWithinFamily) => stayWit" +
                    "hinFamily ? 1 : ");
            
            #line 29 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dimensionUnitOfMeasureBase.NonFamilyMultiplier));
            
            #line default
            #line hidden
            this.Write(";\r\n        \r\n");
            
            #line 31 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
  } 
            
            #line default
            #line hidden
            
            #line 32 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
  if (dimensionUnitOfMeasureBase.UnitGroupName != null) { 
            
            #line default
            #line hidden
            this.Write("        protected override bool IsSameFamily(System.Type typeOfUnitOfMeasure) => " +
                    "typeof(");
            
            #line 33 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dimensionUnitOfMeasureBase.InterfaceName));
            
            #line default
            #line hidden
            this.Write(").IsAssignableFrom(typeOfUnitOfMeasure);\r\n        \r\n");
            
            #line 35 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
  } 
            
            #line default
            #line hidden
            
            #line 36 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
  if ((dimensionUnitOfMeasureBase.Is1DInterface || dimensionUnitOfMeasureBase.UnitGroupName != null) && dimensionUnitOfMeasureBase.Symbol2D != null) { 
            
            #line default
            #line hidden
            this.Write("        protected internal ");
            
            #line 37 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((dimensionUnitOfMeasureBase.Is1DInterface)?"virtual":"override"));
            
            #line default
            #line hidden
            this.Write(" string AreaUnitSymbol => $@\"");
            
            #line 37 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dimensionUnitOfMeasureBase.Symbol2D));
            
            #line default
            #line hidden
            this.Write("\";\r\n        \r\n");
            
            #line 39 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
  } 
            
            #line default
            #line hidden
            
            #line 40 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
  if ((dimensionUnitOfMeasureBase.Is1DInterface || dimensionUnitOfMeasureBase.UnitGroupName != null) && dimensionUnitOfMeasureBase.Symbol3D != null) { 
            
            #line default
            #line hidden
            this.Write("        protected internal ");
            
            #line 41 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((dimensionUnitOfMeasureBase.Is1DInterface)?"virtual":"override"));
            
            #line default
            #line hidden
            this.Write(" string VolumeUnitSymbol => $@\"");
            
            #line 41 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dimensionUnitOfMeasureBase.Symbol3D));
            
            #line default
            #line hidden
            this.Write("\";\r\n        \r\n");
            
            #line 43 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
  } 
            
            #line default
            #line hidden
            
            #line 44 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
  if (dimensionUnitOfMeasureBase.Is2DInterface) { 
            
            #line default
            #line hidden
            this.Write("        protected override int Exponent => 2;\r\n        \r\n");
            
            #line 47 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
  } 
            
            #line default
            #line hidden
            
            #line 48 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
  if (dimensionUnitOfMeasureBase.Is3DInterface) { 
            
            #line default
            #line hidden
            this.Write("        protected override int Exponent => 3;\r\n        \r\n");
            
            #line 51 "G:\Josh\Workspace\NGenericDimensions\src\CodeGenerator\T4DimensionUnitOfMeasure.tt"
  } 
            
            #line default
            #line hidden
            this.Write("    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class T4DimensionUnitOfMeasureBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
